YALB-374: BE Build Alerts
yalesites-org/yalesites_profile pull request #7
Opened 2022-03-31 20:06 UTC by dens0ne

## [YALB-374](https://yaleits.atlassian.net/browse/YALB-374)

### Description of work
- Adds a settings form under `YaleSites` for `Alert settings`
- Programmatically creates a block that can be set in any region and display the values set on the alert settings form.

### Functional testing steps:
- [ ] Login with `terminus drush yaledistributiontest.yalb-374 -- uli`
- [ ] Go to https://yalb-374-yaledistributiontest.pantheonsite.io/admin/yalesites/alert and confirm you can enable the alert. Once enabled, it will show on top of the main content region (we can move it to any other region)
- [ ] Make sure you can update the values and that the fields are updated accordingly
- [ ] When disabled, confirm the block disappears from the content region

2022-04-01 16:51 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    $form['link_wrapper']['link_title'] = [
I'm wondering if we should make the title field required if there is content in the link URL field. Otherwise, we would need a default value if they only supplied a URL. Form API States should do the trick. Or push back if you think this is an incorrect path. https://www.drupal.org/docs/drupal-apis/form-api/conditional-form-fields

2022-04-01 16:57 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +      '#type' => 'url',
The URL field works but I'm wondering if something like a linkit field would be better. (I believe that module is enabled.)

The current URL field does not allow internal paths, so it encourages absolute paths to production which can get messy.

I also think that Linkit fields are easier for authors, but that may not be the case for something like a simple alert. Thoughts?

2022-04-01 17:08 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
I believe this is only a partial solution. Invalidating the render cache is useful for requests that make it all the way to origin, but most logged-out users will hit a caching layer outside of these parts of the stack such as a CDN.

I tested this and can verify that a logged-out user does not see different content if they already hit a cached copy.

The solution may be as simple as bubbling up caching invalidation events to these other services. I believe that's what this module is for? https://www.drupal.org/project/pantheon_advanced_page_cache

Instead, I typically create a separate controller for alert data and then let the alerts load async on the client-side. I don't want to overengineer the solution. Alerts should be simple for now and we can add more complex logic in the future.

2022-04-01 17:12 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
Can we load this service through dependency injection? While loading services through the global Drupal object is functionally the same, it is the less preferred method.

At the moment we are not writing unit/function tests, but using DI can make it easier to mock things in the future.

2022-04-01 17:16 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  public function validateForm(array &$form, FormStateInterface $form_state) {
I don't believe this function does anything if you're just passing through to the parent.

2022-04-01 17:59 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  public function validateForm(array &$form, FormStateInterface $form_state) {
Right, I was thinking about deleting it if there were no real things to validate, and figured at this point either through code review we'll decide if we want to get rid of it, or, add a validation for something I was not accounting for. I'll keep this in mind as I keep working on updates based on feedback.

2022-04-01 18:02 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
I forgot you mentioned that about a custom controller. I'll look into cache tags with the Pantheon module.

2022-04-01 18:39 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
We might not even need it if we use cache tags. I'll double-check.

2022-04-01 18:41 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +      '#markup' => $this->t('Available fields are: <br/> Alert id: @id. <br/> Alert status: @as. <br/> Alert type: @at. <br/> Alert headline: @ah. <br/> Alert message: @am. <br/> Alert link title: @a
We are right at the border of FE and BE. If I was doing this work, I would probably create a custom twig template and send these parameters through a render array. This way Brian can do all of his work at the template level. I'll leave it up to you and @ModulesUnraveled to figure out the best way to hand off work.

```php
// Declare a new template in the module.
function ys_alert_theme() {
  return [
    'ys_alert' => [
      'variables' => [
        'status' => NULL,
        'headline' => '',
        ...etc
    ],
  ];
}
```

```php
// Return the data in a render array using the custom template.
return [
  '#theme' => 'ys_alert',
  '#status' => $config->get('status'),
  '#headline' => $config->get('headline'),
  ... etc
];
```

```twig
{# ys_alert/templates/ys-alert.html.twig #}
<div>
  <div>Status: {{ status }}</div>
  <div>Headline: {{ headline }}</div>
  ...etc
</div>
```

2022-04-01 18:41 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    $config = \Drupal::config('ys_alert.settings');
Please use dependency injection if possible. Your code is 100%, but DI is preferred.

2022-04-01 18:44 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    $alert_status = $config->get('status');
We're not building this site with multilingual in mind, so I may forget about this often in this project. But when possible, I think we should use the t-function whenever we're sending strings to the template.

2022-04-01 18:44 UTC, nJim commented on config/sync/ys_alert.settings.yml
> +headline: 'Headline examlple'
Typo 'example'

2022-04-01 18:45 UTC, nJim commented on config/sync/core.extension.yml
> +  ys_alert: 0
Should we also add this to the profile install file? I hate that we need to manually update this. Seems like config management will still turn all of the right things on in any case.

2022-04-01 18:46 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +  public function blockForm($form, FormStateInterface $form_state) {
I don't believe this function does anything. Safe to remove it? Or do you prefer keeping this kind of boillerplate for future use?

2022-04-01 18:48 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    if (!\Drupal::config('ys_alert.settings')->get('status')) {
Clever. I would have added a conditional to the render array. This approach is much more accurate. 👍

2022-04-01 18:49 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
I'm happy to show my ajax pattern if needed. But let's find the simplest approach first.

2022-04-01 18:51 UTC, nJim requested changes
The form and display are working well. The only technical issue is the cache-busting thing. I added several comments about the code. Some are nit-picky refactors, a few small enhancements, and finally some open questions that you can totally disagree with.

2022-04-01 21:58 UTC, dens0ne commented
@nJim I think I've updated everything here but the cache tags. I have tried multiple approaches without any luck. I reserved the dependency injection portion for the last, so those would be the last 2 things to figure out. But if you don't mind, I'd like to either pair program this with you, or ask for you to take a stab at the caching portion 🙏

2022-04-07 21:21 UTC, dens0ne commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +  public function blockForm($form, FormStateInterface $form_state) {
I didn't want to remove without consulting if we are gonna add permissions. We did not for the admin form, but still wanted to double-check. So, you want me to remove it?

2022-04-07 21:25 UTC, dens0ne commented on config/sync/ys_alert.settings.yml
> +headline: 'Headline examlple'
We probably want to `config-ignore` this at some point, but certainly no typos allowed!

2022-04-08 21:20 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +    \Drupal::service('cache.render')->invalidateAll();
If we need, we'll grab that code from the closed PR. Thanks for putting that cool example together.

2022-04-08 21:23 UTC, dens0ne commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +      '#markup' => $this->t('Available fields are: <br/> Alert id: @id. <br/> Alert status: @as. <br/> Alert type: @at. <br/> Alert headline: @ah. <br/> Alert message: @am. <br/> Alert link title: @a
I missed this one. Still has to be done

2022-04-08 23:07 UTC, dens0ne commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +      '#markup' => $this->t('Available fields are: <br/> Alert id: @id. <br/> Alert status: @as. <br/> Alert type: @at. <br/> Alert headline: @ah. <br/> Alert message: @am. <br/> Alert link title: @a
@nJim I think this is done but I couldn't push the last changes to the multidev. Please feel free to do so or give it a shot locally to the latest commits 🙏

2022-04-09 01:20 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $requestContext;
This property is unused

2022-04-09 01:21 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $pathValidator;
This property is unused

2022-04-09 01:21 UTC, nJim commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $aliasManager;
This property is unused.

2022-04-09 01:23 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    $this->configuration['my_block_settings'] = $form_state->getValue('my_block_settings');
What does this do?

2022-04-09 01:55 UTC, nJim commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    ];
I'm totally nit picking. But if you are editing this file for other changes, you may want to rewrite this in a shorter form. It may not have a measurable impact as things are cached. But it's always nice to reduce unnecessary memory allocation for variables only used once.

```php
    return [
      '#theme' => 'ys_alert',
      '#id' => $config->get('id'),
      '#status' => $config->get('status'),
      '#type' => $config->get('type'),
      '#headline' => $config->get('headline'),
      '#message' => $config->get('message'),
      '#link_title' => $config->get('link_title'),
      '#link_url' => $config->get('link_url'),
    ];
```

2022-04-09 01:56 UTC, nJim requested changes
Looking good. I have a few  more questions before we call this done. See comments.

2022-04-11 16:25 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $requestContext;
Good call, removed.

2022-04-11 16:25 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $pathValidator;
Good call, removed.

2022-04-11 16:25 UTC, dens0ne commented on modules/custom/ys_alert/src/Form/AlertSettings.php
> +  protected $aliasManager;
Good call, removed.

2022-04-11 16:25 UTC, dens0ne commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    $this->configuration['my_block_settings'] = $form_state->getValue('my_block_settings');
Good call, removed.

2022-04-11 16:26 UTC, dens0ne commented on modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
> +    ];
I was thinking about this after I pushed my commit on Friday but ran out of time. I think this makes sense. And I've updated it. Thanks.

2022-04-11 16:31 UTC, dens0ne commented
Thanks for the feedback @nJim, I've pushed the latest changes to the multidev.

2022-04-13 14:44 UTC, nJim approved these changes
Everything looks great. Thank you for the attention to detail. Approved for internal 4K review.

2022-04-18 13:40 UTC, vinmassaro approved these changes

2022-04-18 15:33 UTC, merged